### ISSUE TITLE
Feature suggestion/request

### ISSUE THREAD

**Issue by IAmSalvaMartini** [bmresearch/Anvil#1]
1. An option to just paste the private key instead of having to select a json file
2. Delete a wallet from the list of wallets
3. Sol airdrop option in testnet/devnet configuration

I love the wallet btw, look forward to using the multisig feature

**Comment by hoakbuilds** [comment]
Thanks for your suggestions, I'll happily implement these.

Pasting private key instead of having to select the json file and deleting a wallet from the list (essentially removing from the wallet store) are trivial features to implement.

Airdrop feature on testnet/devnet configurations might be a little more work for a couple reasons.
There's only one wallet store and it makes no distinction on addresses between mainnet/testnet/devnet, which in turn leads to some erratic behavior under the hood. I'll have to see exactly which is the best way to take care of this.

**Comment by hoakbuilds** [comment]
Already took care of your first feature request. Will follow up with the rest later today.

**Comment by hoakbuilds** [comment]
Already took care of feature number two as well. Will follow with the other

**Comment by IAmSalvaMartini** [comment]
Awesome, will check it out

**Comment by IAmSalvaMartini** [comment]
Thank you for the quick reply and addition

**Comment by hoakbuilds** [comment]
You can now request airdrop on testnet and devnet. Thank you for the suggestions, if some other issue/suggestions feel free to open another issue :)
